# Generated by Django 2.1.1 on 2018-10-03 03:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_block', models.IntegerField(validators=[django.core.validators.MaxValueValidator(47), django.core.validators.MinValueValidator(0)])),
                ('duration_block', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(47), django.core.validators.MinValueValidator(0)])),
                ('day', models.DateField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DestacApi.Bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DestacApi.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DestacApi.Person'),
        ),
    ]
