# Generated by Django 2.1.1 on 2018-10-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DestacApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='city',
            field=models.CharField(default='Santiago', max_length=20),
            preserve_default=False,
        ),
    ]
