# Generated by Django 2.1.1 on 2018-10-07 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DestacApi', '0002_auto_20181003_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_destination', to='DestacApi.Terminal')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_origin', to='DestacApi.Terminal')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_block',
            field=models.DateTimeField(),
        ),
    ]
