# Generated by Django 2.1.1 on 2018-10-07 19:50

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DestacApi', '0003_auto_20181007_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='duration_block',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 7, 19, 50, 16, 796841)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DestacApi.Route'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DestacApi.Schedule'),
        ),
    ]
